CREATE TABLE bestellingen(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
KlantId INT NOT NULL,
Product INT NOT NULL,
Aantal INT NOT NULL,
CONSTRAINT [FK_Bestelling_Klant] FOREIGN KEY (KlantId) REFERENCES klanten(KlantId)
);